package littleMaidMobX.registry;

import java.util.HashSet;

import littleMaidMobX.model.maid.ModelLittleMaid_AC;
import littleMaidMobX.model.maid.ModelLittleMaid_Archetype;
import littleMaidMobX.model.maid.ModelLittleMaid_Aug;
import littleMaidMobX.model.maid.ModelLittleMaid_Orign;
import littleMaidMobX.model.maid.ModelLittleMaid_SR2;
import littleMaidMobX.model.maids.ModelLittleMaid_Beverly7;
import littleMaidMobX.model.maids.ModelLittleMaid_Chloe2;
import littleMaidMobX.model.maids.ModelLittleMaid_Elsa5;
import littleMaidMobX.model.maids.ModelLittleMaid_RX0;
import littleMaidMobX.model.maids.ModelMulti_Stef;
import littleMaidMobX.model.maids.ModelMulti_Steve;
import littleMaidMobX.model.maids.MultiModel_Angel;
import littleMaidMobX.model.maids.MultiModel_Aokise;
import littleMaidMobX.model.maids.MultiModel_Beverly2;
import littleMaidMobX.model.maids.MultiModel_Beverly3;
import littleMaidMobX.model.maids.MultiModel_Beverly4;
import littleMaidMobX.model.maids.MultiModel_Beverly5;
import littleMaidMobX.model.maids.MultiModel_Beverly6;
import littleMaidMobX.model.maids.MultiModel_ChibiNeko;
import littleMaidMobX.model.maids.MultiModel_DogAngel;
import littleMaidMobX.model.maids.MultiModel_DogAngel2;
import littleMaidMobX.model.maids.MultiModel_DressYukari;
import littleMaidMobX.model.maids.MultiModel_Elsa;
import littleMaidMobX.model.maids.MultiModel_Elsa2;
import littleMaidMobX.model.maids.MultiModel_Elsa3;
import littleMaidMobX.model.maids.MultiModel_Elsa4;
import littleMaidMobX.model.maids.MultiModel_Elsie;
import littleMaidMobX.model.maids.MultiModel_Evelyn3;
import littleMaidMobX.model.maids.MultiModel_ExtraArms;
import littleMaidMobX.model.maids.MultiModel_Kagami;
import littleMaidMobX.model.maids.MultiModel_Kelo;
import littleMaidMobX.model.maids.MultiModel_MS;
import littleMaidMobX.model.maids.MultiModel_MS1;
import littleMaidMobX.model.maids.MultiModel_Mabel;
import littleMaidMobX.model.maids.MultiModel_NM;
import littleMaidMobX.model.maids.MultiModel_NM1;
import littleMaidMobX.model.maids.MultiModel_Pawapro;
import littleMaidMobX.model.maids.MultiModel_Petit;
import littleMaidMobX.model.maids.MultiModel_QB;
import littleMaidMobX.model.maids.MultiModel_SA;
import littleMaidMobX.model.maids.MultiModel_Shion;
import littleMaidMobX.model.maids.MultiModel_Tenshi;
import littleMaidMobX.model.maids.MultiModel_Utsuho;
import littleMaidMobX.model.maids.MultiModel_VUD1;
import littleMaidMobX.model.maids.MultiModel_Yomu;
import littleMaidMobX.model.maids.MultiModel_Yukari;
import littleMaidMobX.model.maids.MultiModel_Yukkuri;
import littleMaidMobX.model.maids.MultiModel_bgs;
import littleMaidMobX.model.maids.MultiModel_brs;
import littleMaidMobX.model.maids.MultiModel_ch;
import littleMaidMobX.model.maids.MultiModel_chrno;
import littleMaidMobX.model.maids.MultiModel_chu;
import littleMaidMobX.model.maids.MultiModel_dm;
import littleMaidMobX.model.maids.MultiModel_long;
import littleMaidMobX.model.maids.MultiModel_mahoro;
import littleMaidMobX.model.maids.MultiModel_naz;
import littleMaidMobX.model.maids.MultiModel_st;
import littleMaidMobX.model.maids.MultiModel_suika;
import littleMaidMobX.model.maids.MultiModel_taremimi;
import littleMaidMobX.model.maids.MultiModel_tareusa;
import littleMaidMobX.model.maids.MultiModel_twinD;
import littleMaidMobX.model.maids.MultiModel_usagi;

public class ModelRegistry {
	public static final HashSet<Class> list = new HashSet<Class>();
	static
	{
		list.add(ModelLittleMaid_AC.class);
		list.add(ModelLittleMaid_Archetype.class);
		list.add(ModelLittleMaid_Aug.class);
		list.add(ModelLittleMaid_Beverly7.class);
		list.add(ModelLittleMaid_Chloe2.class);
		list.add(ModelLittleMaid_Elsa5.class);
		list.add(ModelLittleMaid_Orign.class);
		list.add(ModelLittleMaid_RX0.class);
		list.add(ModelLittleMaid_SR2.class);
		list.add(ModelMulti_Stef.class);
		list.add(ModelMulti_Steve.class);
		list.add(MultiModel_Angel.class);
		list.add(MultiModel_Aokise.class);
		list.add(MultiModel_Beverly2.class);
		list.add(MultiModel_Beverly3.class);
		list.add(MultiModel_Beverly4.class);
		list.add(MultiModel_Beverly5.class);
		list.add(MultiModel_Beverly6.class);
		list.add(MultiModel_bgs.class);
		list.add(MultiModel_brs.class);
		list.add(MultiModel_ch.class);
		list.add(MultiModel_ChibiNeko.class);
		list.add(MultiModel_chrno.class);
		list.add(MultiModel_chu.class);
		list.add(MultiModel_dm.class);
		list.add(MultiModel_DogAngel.class);
		list.add(MultiModel_DogAngel2.class);
		list.add(MultiModel_DressYukari.class);
		list.add(MultiModel_Elsa.class);
		list.add(MultiModel_Elsa2.class);
		list.add(MultiModel_Elsa3.class);
		list.add(MultiModel_Elsa4.class);
		list.add(MultiModel_Elsie.class);
		list.add(MultiModel_Evelyn3.class);
		list.add(MultiModel_ExtraArms.class);
		list.add(MultiModel_Kagami.class);
		list.add(MultiModel_Kelo.class);
		list.add(MultiModel_long.class);
		list.add(MultiModel_Mabel.class);
		list.add(MultiModel_mahoro.class);
		list.add(MultiModel_MS.class);
		list.add(MultiModel_MS1.class);
		list.add(MultiModel_naz.class);
		list.add(MultiModel_NM.class);
		list.add(MultiModel_NM1.class);
		list.add(MultiModel_Pawapro.class);
		list.add(MultiModel_Petit.class);
		list.add(MultiModel_QB.class);
		list.add(MultiModel_SA.class);
		list.add(MultiModel_Shion.class);
		list.add(MultiModel_st.class);
		list.add(MultiModel_suika.class);
		list.add(MultiModel_taremimi.class);
		list.add(MultiModel_tareusa.class);
		list.add(MultiModel_Tenshi.class);
		list.add(MultiModel_twinD.class);
		list.add(MultiModel_usagi.class);
		list.add(MultiModel_Utsuho.class);
		list.add(MultiModel_VUD1.class);
		list.add(MultiModel_Yomu.class);
		list.add(MultiModel_Yukari.class);
		list.add(MultiModel_Yukkuri.class);
	}

}
